### PR TITLE
pdfcpu 0.5.0

### PR DESCRIPTION
**Pull request by christian-heusel**
- chore: update pdfcpu to version 0.5.0
- chore: bump go in the dockerfile to version 1.21
- fix: skip images that cannot be decoded instead of crashing

### CODE REVIEW

**Comment by Splines** [comment]
Are there any plans to merge this?

**Comment by henrixapp** [comment]
If I remember correctly I have not merged, because the issues of https://github.com/henrixapp/pdfcomprezzor/pull/10#issuecomment-1685116521 are still not adressed.

There seems to be a problem with iOS(default annotation app) on latex generated files. I did not find the exact reproducability. This lead to some improvement in the testing situation that I have yet to push.

If @Splines and @christian-heusel  can confirm that this update is working on some pdfs, I am glad to merge this already (adding CI can be done later).

**Comment by Splines** [comment]
Sorry, I don't possess any device made by Apple, so I cannot test this.

**Comment by henrixapp** [comment]
I am talking about general pdfs. It suffices for me to only check some, not this "special" case.

**Comment by christian-heusel** [comment]
Closed in favor of #12

**Pull request closed without merging**
